server:
  port: 8000
  servlet:
    context-path: /member

spring:
  datasource:
    url: jdbc:mysql://192.168.56.10/shadowmall_ums
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
# 每个微服务必须设置名称
  application:
    name: shadow-member
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848  # nacos服务注册中心地址
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml # mapper.xml文件位置
  global-config:
    db-config:
      id-type: auto # 自增主键

