server:
  port: 10000
  servlet:
    context-path: /product

spring:
  datasource:
    url: jdbc:mysql://192.168.56.10/shadowmall_pms
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
# 每个微服务必须设置名称
  application:
    name: shadow-product
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848  # nacos服务注册中心地址
#    alicloud: # OSS配置
#        access-key: LTAI4Fc1uRrRjBSPD9YGaFep
#        secret-key: 5QSzN7uHD2sKb108ovtPsDZsVA4kG0
#        oss:
#          endpoint: oss-cn-shanghai.aliyuncs.com



mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml # mapper.xml文件位置
  global-config:
    db-config:
      id-type: auto # 自增主键
      logic-delete-value: 1 # 逻辑删除值1
      logic-not-delete-value: 0 # 逻辑删除值 0
logging:
  level:
    com.shadow.mall.product: debug